name: traefik-ryanjyoder
version: "v1.7.0-rc5"
summary: The Cloud Native Edge Router
description: |
        Træfik is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy. Træfik integrates with your existing infrastructure components (Docker, Swarm mode, Kubernetes, Marathon, Consul, Etcd, Rancher, Amazon ECS, ...) and configures itself automatically and dynamically. Pointing Træfik at your orchestrator should be the only configuration step you need.

grade: stable
confinement: strict

apps:
  traefik:
    command: traefik -c $SNAP_DATA/traefik.toml
    daemon: simple
    plugs: [network-bind]

parts:
  config:
    plugin: dump
    source: ./config

  traefik:
    plugin: dump
    override-pull: |
            case "$SNAPCRAFT_ARCH_TRIPLET" in
                i386-linux-gnu)
                        echo i386
                        wget -O traefik https://github.com/containous/traefik/releases/download/v1.7.0-rc5/traefik_linux-386
                        ;;

                x86_64-linux-gnu)
                        echo arm64
                        wget -O traefik https://github.com/containous/traefik/releases/download/v1.7.0-rc5/traefik_linux-amd64
                        ;;

                arm=linux-gnu)
                        echo arm
                        wget -O traefik https://github.com/containous/traefik/releases/download/v1.7.0-rc5/traefik_linux-arm
                        ;;

                *)
                        echo "Arch type unknown: $SNAPCRAFT_ARCH_TRIPLET"
                        exit 1

            esac
            chmod 755 traefik


